### ISSUE TITLE
🐞 [Bug]: Typo in information line during `init`

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-cli#115]
### What happened?

Once you init you are prompted with the various questions to start the node & farmer.

```Specify the chain to farm (defaults to 'Gemini3c', press enter to use the default):```

If the user types what is listed they are given an error

```given chain: `Gemini3c` is not recognized!```

![image](https://user-images.githubusercontent.com/31865152/222041839-5582230f-ba95-4b5e-9ee5-f8e63bbd31e0.png)

When left blank it works fine and uses the default of `gemini-3c`

### Version

CLI v0.1.7 Alpha

### platform

- [ ] linux
- [X] windows
- [ ] macos

### Expected behavior

to show the proper chainspec default of `gemini-3c`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ozgunozerk** [comment]
thanks for noticing this, I accidentally introduced a breaking change. I'll issue a new release
