### ISSUE TITLE
[Epic]: Track CLI adoption from Telemetry

### ISSUE THREAD

**Issue by stefanopepe** [subspace/subspace-cli#137]
### Summary

This initiative tracks how many nodes are using the Subspace CLI and which version they are using. The goal is to measure CLI adoption over time and the time needed by the community to follow new releases. The plan is to define a CLI version to make it distinguishable from the Substrate node in the Telemetry, take Telemetry snapshots over time, and visualize the data in our product metrics dashboard.

### Intended Outcome

Subspace CLI was launched to simplify onboarding farmers, executors, and node operators. We haven’t any tracker in the codebase, and we won’t add one to preserve our community privacy, but we want to measure how many nodes are using the CLI, and which version.

We are successful if we can track the CLI versions (and distinguish them from normal Substrate RPC nodes) in the telemetry. We are _very_ successful if we know the CLI adoption over time and measure the time the community needs to follow new releases.

### How Will it Work

From a user standpoint, nothing should change. We wouldn’t include any tracker other than connecting to the Telemetry, as already happens.

We would use a node ID that makes it distinguishable from the standard Substrate node in the Telemetry.

**Comment by ozgunozerk** [comment]
This is already implemented via #127 
Closing
