### ISSUE TITLE
[Epic]: Integration between CLI and User Status on Discord

### ISSUE THREAD

**Issue by stefanopepe** [subspace/subspace-cli#138]
### Summary
This cross-functional team initiative connects farmers' Nodes to their Discord status, to improve community engagement. The goal is to leverage the active community of farmers on social media channels and engage with them across platforms. The document provides a link to a product brief for more context and includes a journal for tracking next steps.

### Intended Outcome
This initiative wants to connect their Node to a Discord status, to improve the engagement.
Our community of farmers is very active on our social media channels, and the Community team can engage them across our technical platforms, beginning with the CLI.

### How will it work
(open for discussion below)

**Comment by stefanopepe** [comment]
High-level, how is this going to work? Please validate below:
1. At launch, CLI asks for the Discord account ID
2. CLI calls Discord API and sends data
3. Discord manages the status based on farming data

cc @ImmaZoni @ozgunozerk

**Comment by nazar-pc** [comment]
I think it needs to integrate with desktop app, in which case I don't think we need to ask for the ID. Also depends heavily on whether we want to maintain some backend APIs or limit to client-side integration with desktop app.
