### ISSUE TITLE
🎁 [Feature Request]: Add command to get current version

### ISSUE THREAD

**Issue by extSunset** [subspace/subspace-cli#146]
### What is the feature you would like to see?

The ability to somehow determine the version of an individual executable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ozgunozerk** [comment]
you can get it by `init` command, but I can see how that is not intuitive and can be harmful (this will override your config).
Will do, thanks for the suggestion!

**Comment by ozgunozerk** [comment]
`-V` (careful, capital letter), and `--verbose` will do the job. PR is under review #147
