### ISSUE TITLE
🐞 [Bug]: Synchronization issues

### ISSUE THREAD

**Issue by okannako** [subspace/subspace-cli#150]
### What happened?

For 4 days it has been struggling to synchronize to the system and then it started giving these errors and keeps stopping. It restarts spontaneously because I set the service but 

```
The application panicked (crashed).
Message:  range end index 8 out of range for slice of length 0
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-db-0.4.4/src/table.rs:210
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   0: tokio::task::runtime.spawn with kind=block_on task.name= task.id=43 loc.file="/home/runner/.cargo/git/checkouts/subspace-5c1447fb849a5554/901340e/crates/subspace-farmer/src/utils.rs" loc.line=64 loc.col=35
      at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/util/trace.rs:16
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
The application panicked (crashed).
Message:  Panic if background thread panicked: Any { .. }
Location: /home/runner/.cargo/git/checkouts/subspace-5c1447fb849a5554/901340e/crates/subspace-farmer/src/utils.rs:31
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   0: tokio::task::runtime.spawn with kind=task task.name=subspace-sdk-node-NakoTurk-task-manager task.id=2173 loc.file="/home/runner/.cargo/git/checkouts/subspace-sdk-cf03f5a296714cdf/dfa443f/src/node/mod.rs" loc.line=1345 loc.col=14
      at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/util/trace.rs:16
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

```
edEof, message: "failed to fill whole buffer" }))
Farmer started successfully!
2023-03-23T19:06:03.986758Z  INFO single_disk_plot{disk_farm_index=0}: subspace_farmer::single_disk_plot: Subscribing to slot info notifications
The application panicked (crashed).
Message:  Cannot block the current thread from within a runtime. This happens because a function attempted to block the current thread while the thread is being used to drive asynchronous tasks.
Location: /home/runner/.cargo/git/checkouts/subspace-sdk-cf03f5a296714cdf/dfa443f/src/farmer.rs:647
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### Version

subspace-cli-ubuntu-x86_64-v3-v0.1.10-alpha

### platform

- [X] linux
- [ ] windows
- [ ] macos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by okannako** [comment]
I'll write after I try it. Thanks.

> Thanks for the submission! We had a duplicate of this issue I guess (#148). Can you please try with latest release (which is v0.1.11), and report if the issue is still present? To our experiments, this issue is resolved :)

**Comment by Screem0033** [comment]
what command to update? (which is v0.1.11)

**Comment by Screem0033** [comment]
> Спасибо за представление! Думаю, у нас был дубликат этого выпуска ( #148 ). Не могли бы вы попробовать последнюю версию (v0.1.11) и сообщить, сохраняется ли проблема? К нашим экспериментам этот вопрос решен :)

what command to update? (which is v0.1.11)????

**Comment by ozgunozerk** [comment]
Yes, you downloaded it 👍 
You simply should run this executable from now on instead of v0.1.10. This is the update procedure :)
Nothing else is required!

**Comment by ozgunozerk** [comment]
Probably you are confused by the `update` word. 
Whenever we release a new version (you can check the releases from the repository main page), 
- you can download the executable (just like you did for downloading v0.1.11). 
- you can run the new executable (however you run the previous version, just follow the same steps, whether on a server or on your daily machine, up to you)
- voila! you basically "updated" your software.
