### ISSUE TITLE
🐞 [Bug]: Inspect reward events and revamp the logic for `# farmed blocks`

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-cli#163]
### What is the feature you would like to see?

Right now, `farmed blocks count` refers to every solution found by the farmer. However, finding a solution does not necessarily mean this very solution will be used for the farming of the block. In other words, there can be multiple solutions for a block, and another solution can be picked as the final solution. 

The end-user probably does only care about `how many blocks they farmed`, not `how many solutions they have found`. 

Will update CLI code accordingly once SDK can expose `reward` events

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by i1i1** [comment]
Depends on subspace/subspace-sdk#161
