### ISSUE TITLE
🐞 [Bug]: Summary file cannot be read

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-cli#197]
### What happened?

There are 3 reasons:
- due to same file being shared, but cursor is not manipulated, null characters are inserted to the file, and utf8 standards are broken
- the path for the summary was not set to `cache` in one place
- read permission for `summary` was not set after revamping the summary

### Version

v0.4.0

### platform

- [X] linux
- [X] windows
- [X] macos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spacrypto** [comment]
Hello.Tell me please, what could be the problem. When I start a node with version v0.3.3-alpha - v0.4.1 (core dumped!) "Starting node... Illegal instruction (core dumped)" Version v0.3.2 works well.
My Processor i7-4578U

**Comment by ozgunozerk** [comment]
Are you sure you are using the correct version? Your CPU seems old, you can find more about this on the release notes.

**Comment by spacrypto** [comment]
./subspace-cli-ubuntu-x86_64-v2-v0.4.1-alpha farm
Starting node ...
Illegal instruction (core dumped)
=========================================
./subspace-cli-ubuntu-x86_64-v3-v0.4.1-alpha farm
Starting node ...
Illegal instruction (core dumped)
==========================================
v2-v0.3.2 and v3-v0.3.2 Working!

**Comment by spacrypto** [comment]
vendor_id       : GenuineIntel
cpu family      : 6
model           : 69
model name      : Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
stepping        : 1
microcode       : 0x26
cpu MHz         : 3004.803
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
vmx flags       : vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds mmio_unknown
bogomips        : 6002.21
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 69
model name      : Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
stepping        : 1
microcode       : 0x26
cpu MHz         : 3108.704
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm con

**Comment by spacrypto** [comment]
echo 'BEGIN {
    while (!/flags/) if (getline < "/proc/cpuinfo" != 1) exit 1
    if (/lm/&&/cmov/&&/cx8/&&/fpu/&&/fxsr/&&/mmx/&&/syscall/&&/sse2/) level = 1
    if (level == 1 && /cx16/&&/lahf/&&/popcnt/&&/sse4_1/&&/sse4_2/&&/ssse3/) level = 2
    if (level == 2 && /avx/&&/avx2/&&/bmi1/&&/bmi2/&&/f16c/&&/fma/&&/abm/&&/movbe/&&/xsave/) level = 3
    if (level == 3 && /avx512f/&&/avx512bw/&&/avx512cd/&&/avx512dq/&&/avx512vl/) level = 4
    if (level > 0) { print "CPU supports x86-64-v" level; exit level + 1 }
    exit 1
}' | awk -f -

**CPU supports x86-64-v3**

**Comment by ozgunozerk** [comment]
As I suspected, if v2 works, then I think there is no reason to worry! I think your CPU supports v2 instead of v3
