### ISSUE TITLE
lift off command `subspace-cli farm` from subspace-cli init can be confusing and inaccurate

### ISSUE THREAD

**Issue by achiurizo** [subspace/subspace-cli#65]
When running `subspace-cli init`, the prompt follows with a "Lift Off!" command:

```sh
Ready for lift off! Run the follow command to begin:
`./subspace-cli farm`
```

For folks that have downloaded the [release binaries](https://github.com/subspace/subspace-cli/releases), the binary name may not match this (like `./subspace-cli-ubuntu-x86_64-v0.1.0-alpha`). We should make this output match the actual binary name or just simply the prompt to just tell the end-users to run `farm`

**Comment by ozgunozerk** [comment]
We have this, do you think it is not enough?
<img width="952" alt="image" src="https://user-images.githubusercontent.com/32795992/204496335-3f52ebc2-a651-4df1-9af4-7e741511821b.png">
If so, yes I can update it
