### ISSUE TITLE
Log File takes up remaining space on disk.

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-cli#68]
When plotting with the CLI on Windows 11, the log file will consume the rest of the available space on the device. In my case I had ~90GB free, and was attempting a 25GB plot. After running the cli I face this error

```
      at C:\Users\runneradmin\.cargo\git\checkouts\substrate-7bc20b373ca3e834\6d57dbc\frame\executive\src\lib.rs:404
   1: sc_service::client::client::import_block
      at C:\Users\runneradmin\.cargo\git\checkouts\substrate-7bc20b373ca3e834\6d57dbc\client\service\src\client\client.rs:1722
   2: subspace_cli::commands::farm::prepare_farming
      at src\commands\farm.rs:152
```

And then the log file proceeded to fill up the remaining space available, in this case ended up being a 46GB log file.
![image](https://user-images.githubusercontent.com/31865152/204583620-83d58b93-91d0-4ab8-ae56-0da132f4e4b0.png)

leaving me with 0 Bytes available on my system
![image](https://user-images.githubusercontent.com/31865152/204583730-67d04d5e-dbd0-41d5-b165-d2afccafbe57.png)

**Comment by ozgunozerk** [comment]
I can confirm this, for me it was 60 GB of logs. 
Let me elaborate on the issue. We are using rotating logs, which will rotate on each day, and total of 7 days of history will be kept. 

However, the current log level is too verbose for 7 days of log (this was not the case for desktop). In other words, the logging from `farmer` and `node` has significantly increased by the monorepo side. 

There are 2 solutions:
- reduce the depth of logging.
- lower the amount of data we are storing (maybe 10 minutes rotation with 5 files)?

I'm in favor of reducing the depth of logging, but we might want some of the lower level debugging info for tracking issues.

@nazar-pc , what are your thoughts on this?

**Comment by nazar-pc** [comment]
@ozgunozerk the default log level must be `info`, anything above that must be opt-in.
On the size question, does the library support limiting size, not just age of log entries? Let's say, store last 256MiB of logs only. That is a typical feature for log rotation.

**Comment by ozgunozerk** [comment]
Ok, we were logging `debug` level beforehand. That's good news! 

I'll check tomorrow on adding a further restriction for size. I recall there were none in tracing (but I'll double check) and hence I implemented the rotating logs functionality to eliminate infinitely-growing logs in back in *subspace-desktop* time.

**Comment by ozgunozerk** [comment]
Closing in favor of #70
