### ISSUE TITLE
implement `subspace-cli farm`

### ISSUE THREAD

**Issue by achiurizo** [subspace/subspace-cli#7]
Following the merge of the[ initial SDK API](https://github.com/subspace/subspace-sdk/pull/2), let's implement the `farm` functionality for CLI.

**Comment by ozgunozerk** [comment]
I believe this should be an epic, including the other 2 issues about farmer (quite and verbose mode), along with progression bar

**Comment by achiurizo** [comment]
Let's close this out and use the other 2 issues to represent this then. 🙏
